CREATE TABLE [dbo].[DimCustomer] (

	[CustomerKey] int NULL, 
	[GeographyKey] int NULL, 
	[CustomerAlternateKey] varchar(8000) NULL, 
	[Title] varchar(8000) NULL, 
	[FirstName] varchar(8000) NULL, 
	[MiddleName] varchar(8000) NULL, 
	[LastName] varchar(8000) NULL, 
	[NameStyle] bit NULL, 
	[BirthDate] date NULL, 
	[MaritalStatus] char(1) NULL, 
	[Suffix] varchar(8000) NULL, 
	[Gender] varchar(8000) NULL, 
	[EmailAddress] varchar(8000) NULL, 
	[YearlyIncome] decimal(19,4) NULL, 
	[TotalChildren] int NULL, 
	[NumberChildrenAtHome] int NULL, 
	[EnglishEducation] varchar(8000) NULL, 
	[SpanishEducation] varchar(8000) NULL, 
	[FrenchEducation] varchar(8000) NULL, 
	[EnglishOccupation] varchar(8000) NULL, 
	[SpanishOccupation] varchar(8000) NULL, 
	[FrenchOccupation] varchar(8000) NULL, 
	[HouseOwnerFlag] char(1) NULL, 
	[NumberCarsOwned] int NULL, 
	[AddressLine1] varchar(8000) NULL, 
	[AddressLine2] varchar(8000) NULL, 
	[Phone] varchar(8000) NULL, 
	[DateFirstPurchase] date NULL, 
	[CommuteDistance] varchar(8000) NULL
);