CREATE TABLE [dbo].[DimEmployee] (

	[EmployeeKey] int NULL, 
	[ParentEmployeeKey] int NULL, 
	[EmployeeNationalIDAlternateKey] varchar(8000) NULL, 
	[ParentEmployeeNationalIDAlternateKey] varchar(8000) NULL, 
	[SalesTerritoryKey] int NULL, 
	[FirstName] varchar(8000) NULL, 
	[LastName] varchar(8000) NULL, 
	[MiddleName] varchar(8000) NULL, 
	[NameStyle] bit NULL, 
	[Title] varchar(8000) NULL, 
	[HireDate] date NULL, 
	[BirthDate] date NULL, 
	[LoginID] varchar(8000) NULL, 
	[EmailAddress] varchar(8000) NULL, 
	[Phone] varchar(8000) NULL, 
	[MaritalStatus] char(1) NULL, 
	[EmergencyContactName] varchar(8000) NULL, 
	[EmergencyContactPhone] varchar(8000) NULL, 
	[SalariedFlag] bit NULL, 
	[Gender] char(1) NULL, 
	[PayFrequency] int NULL, 
	[BaseRate] decimal(19,4) NULL, 
	[VacationHours] smallint NULL, 
	[SickLeaveHours] smallint NULL, 
	[CurrentFlag] bit NULL, 
	[SalesPersonFlag] bit NULL, 
	[DepartmentName] varchar(8000) NULL, 
	[StartDate] date NULL, 
	[EndDate] date NULL, 
	[Status] varchar(8000) NULL
);