CREATE TABLE [dbo].[DimProduct] (

	[ProductKey] int NULL, 
	[ProductAlternateKey] varchar(8000) NULL, 
	[ProductSubcategoryKey] int NULL, 
	[WeightUnitMeasureCode] char(3) NULL, 
	[SizeUnitMeasureCode] char(3) NULL, 
	[EnglishProductName] varchar(8000) NULL, 
	[SpanishProductName] varchar(8000) NULL, 
	[FrenchProductName] varchar(8000) NULL, 
	[StandardCost] decimal(19,4) NULL, 
	[FinishedGoodsFlag] bit NULL, 
	[Color] varchar(8000) NULL, 
	[SafetyStockLevel] smallint NULL, 
	[ReorderPoint] smallint NULL, 
	[ListPrice] decimal(19,4) NULL, 
	[Size] varchar(8000) NULL, 
	[SizeRange] varchar(8000) NULL, 
	[Weight] float NULL, 
	[DaysToManufacture] int NULL, 
	[ProductLine] char(2) NULL, 
	[DealerPrice] decimal(19,4) NULL, 
	[Class] char(2) NULL, 
	[Style] char(2) NULL, 
	[ModelName] varchar(8000) NULL, 
	[EnglishDescription] varchar(8000) NULL, 
	[StartDate] datetime2(3) NULL, 
	[EndDate] datetime2(3) NULL, 
	[Status] varchar(8000) NULL
);