CREATE TABLE [dbo].[FactResellerSales] (

	[ProductKey] int NULL, 
	[OrderDateKey] int NULL, 
	[DueDateKey] int NULL, 
	[ShipDateKey] int NULL, 
	[ResellerKey] int NULL, 
	[EmployeeKey] int NULL, 
	[PromotionKey] int NULL, 
	[CurrencyKey] int NULL, 
	[SalesTerritoryKey] int NULL, 
	[SalesOrderNumber] varchar(8000) NULL, 
	[SalesOrderLineNumber] int NULL, 
	[RevisionNumber] int NULL, 
	[OrderQuantity] smallint NULL, 
	[UnitPrice] decimal(19,4) NULL, 
	[ExtendedAmount] decimal(19,4) NULL, 
	[UnitPriceDiscountPct] float NULL, 
	[DiscountAmount] float NULL, 
	[ProductStandardCost] decimal(19,4) NULL, 
	[TotalProductCost] decimal(19,4) NULL, 
	[SalesAmount] decimal(19,4) NULL, 
	[TaxAmt] decimal(19,4) NULL, 
	[Freight] decimal(19,4) NULL, 
	[CarrierTrackingNumber] varchar(8000) NULL, 
	[CustomerPONumber] varchar(8000) NULL, 
	[OrderDate] datetime2(3) NULL, 
	[DueDate] datetime2(3) NULL, 
	[ShipDate] datetime2(3) NULL
);